--DLL Exec. 1.0

CREATE DATABASE filme_00;

USE filme_00;

CREATE TABLE Genero
(
	IdGenero INT PRIMARY KEY IDENTITY,
	Genero VARCHAR(30) NOT NULL,
)

CREATE TABLE Filme
(
	IdFilme INT PRIMARY KEY IDENTITY,
	IdGenero INT FOREIGN KEY REFERENCES Genero(IdGenero),
	Filme VARCHAR(100) NOT NULL
)